# .goreleaser.yaml
version: 2

env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - REPO=github.com/maahsome/ktrouble

before:
  hooks:
    - go mod download

builds:
  - id: general
    ldflags:
      - -X ktrouble/cmd.semVer=v{{ .Version }}
      - -X ktrouble/cmd.buildDate={{ .CommitDate }}
      - -X ktrouble/cmd.gitCommit={{ .Commit }}
      - -X ktrouble/cmd.gitRef=refs/tags/{{ .Tag }}
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64

archives:
  - ids: [general]
    builds:
      - general
    formats: [tar.gz]
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - none*  # This preserves the old behavior of only including the binary

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Tag }}-next"

brews:
  - name: ktrouble
    ids:
      - general
    goarm: 6
    repository:
      owner: maahsome
      name: homebrew-tap
      token: "{{ .Env.MAAHSOME_PAT }}"
    url_template: "https://github.com/maahsome/ktrouble/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Christopher Maahs
      email: cmaahs@gmail.com
    directory: Formula
    homepage: "https://github.com/maahsome/ktrouble/"
    description: "A CLI tool built to help with troubleshooting inside kubernetes"
    test: |
      system "#{bin}/ktrouble --help"
    install: |
      bin.install "ktrouble"

